# Problem 1 

In [1]:
import numpy as np

arr=np.array([1,738,37,1000,2])

print(np.sort(arr))


[   1    2   37  738 1000]


# Problem 2

In [45]:
arr2 = np.array([10,15,30,45,60])


arr3=np.arange(5,15)
print(arr3) 
arr4=np.arange(50,100,5)
print(arr4)

arr5=np.zeros(10)
print(arr5)

arr6=np.ones(10)
print(arr6)

arr7=np.linspace(0,100,5)
print(arr7)

arr8=np.random.randint(10,30,5)
print(arr8)

arr9=np.random.uniform(-1,1,size=10)
print(arr9)


arr10=np.random.randint(10,50,size=(3,5))
print(arr10)


satirS,sutunS=arr10.shape
satirT=np.sum(arr10,axis=1)
sutunT=np.sum(arr10,axis=0)
toplam=satirS+sutunS
print(toplam)
print(satirT)
print(sutunT)


max1=np.max(arr10)
min1=np.min(arr10)
orrt=np.mean(arr10)
print(min1,max1,orrt)
enbuyukindex=np.unravel_index(np.argmax(arr10), arr10.shape)
print(enbuyukindex )


dizi=np.arange(10,21)
print(dizi[0:3])

print(dizi[::-1])


print(arr10[0:1])


print(arr10[1][2])
print(arr10[1:2,2:3])


print(arr10[0:3,0:1])

print(np.power(arr10,2))


arr12=np.arange(-50,50)
print(arr12[arr12>=0])


[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[19 15 22 21 26]
[-0.56198293 -0.42254083 -0.38876287  0.42109534  0.97014917  0.72191744
  0.15451781  0.02735737 -0.49117963 -0.38243536]
[[27 44 30 38 36]
 [30 25 19 29 11]
 [39 27 48 31 40]]
8
[175 114 185]
[96 96 97 98 87]
11 48 31.6
(2, 2)
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[[27 44 30 38 36]]
19
[[19]]
[[27]
 [30]
 [39]]
[[ 729 1936  900 1444 1296]
 [ 900  625  361  841  121]
 [1521  729 2304  961 1600]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
