# Problem 1

In [12]:
import numpy as np
import random
arr = np.random.randint(0,10,6)# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
print(arr)
boyut = arr.shape
print(boyut)

arr2=arr.reshape(2,3)

print(arr2)

print(arr2.ndim)


[7 7 5 9 0 1]
(6,)
[[7 7 5]
 [9 0 1]]
2


# Problem 2

In [19]:
arr3= np.arange(1,10,2)
print(arr3)

a,b,c= np.split(arr3,[2,4])
print(a)
print(b)
print(c)

re = np.concatenate([a,b,c])
print(re)


[1 3 5 7 9]
[1 3]
[5 7]
[9]
[1 3 5 7 9]


# Problem 3

In [30]:
dizi = np.arange(5,101,2)
dizi2 = np.random.choice(dizi,10,replace=False)
print(dizi2)
print(dizi2.ndim)
print(dizi2.shape)
print(dizi2.size)
print(dizi2.dtype)


[99 79 97 91 61 13 59 75 83 67]
1
(10,)
10
int32
